= Cheatsheets

[[NetworkOptions]]
== NetworkOptions

++++
 @author <a href="http://tfox.org">Tim Fox</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
Set the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Set the TCP send buffer size
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
Set the value of traffic class
+++
|===

[[DeliveryOptions]]
== DeliveryOptions

++++
 Delivery options are used to configure message delivery.
 <p>
 Delivery options allow to configure delivery timeout and message codec name, and to provide any headers
 that you wish to send with the message.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[codecName]]`codecName`|`String`|
+++
Set the codec name.
+++
|[[sendTimeout]]`sendTimeout`|`Number (long)`|
+++
Set the send timeout.
+++
|===

[[OpenOptions]]
== OpenOptions

++++
 Describes how an link should be opened.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[create]]`create`|`Boolean`|
+++
Set whether the file should be created if it does not already exist.
+++
|[[createNew]]`createNew`|`Boolean`|
+++
Set whether the file should be created and fail if it does exist already.
+++
|[[deleteOnClose]]`deleteOnClose`|`Boolean`|
+++
Set whether the file should be deleted when it's closed, or the JVM is shutdown.
+++
|[[dsync]]`dsync`|`Boolean`|
+++
Set whether every write to the file's content  ill be written synchronously to the underlying hardware.
+++
|[[perms]]`perms`|`String`|
+++
Set the permissions string
+++
|[[read]]`read`|`Boolean`|
+++
Set whether the file is to be opened for reading
+++
|[[sparse]]`sparse`|`Boolean`|
+++
Set whether a hint should be provided that the file to created is sparse
+++
|[[sync]]`sync`|`Boolean`|
+++
Set whether every write to the file's content and meta-data will be written synchronously to the underlying hardware.
+++
|[[truncateExisting]]`truncateExisting`|`Boolean`|
+++
Set whether the file should be truncated to zero length on opening if it exists and is opened for write
+++
|[[write]]`write`|`Boolean`|
+++
Set whether the file is to be opened for writing
+++
|===

[[JksOptions]]
== JksOptions

++++
 Key or trust store options configuring private key and/or certificates based on Java Keystore files.
 <p>
 When used as a key store, it should point to a store containing a private key and its certificate.
 When used as a trust store, it should point to a store containing a list of trusted certificates.
 <p>
 The store can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = HttpServerOptions.httpServerOptions();
 options.setKeyStore(new JKSOptions().setPath("/mykeystore.jks").setPassword("foo"));
 </pre>

 Or directly provided as a buffer:
 <p>

 <pre>
 Buffer store = vertx.fileSystem().readFileSync("/mykeystore.jks");
 options.setKeyStore(new JKSOptions().setValue(store).setPassword("foo"));
 </pre>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[password]]`password`|`String`|
+++
Set the password for the key store
+++
|[[path]]`path`|`String`|
+++
Set the path to the key store
+++
|[[value]]`value`|`Buffer`|
+++
Set the key store as a buffer
+++
|===

[[VertxOptions]]
== VertxOptions

++++
 Instances of this class are used to configure link instances.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[blockedThreadCheckInterval]]`blockedThreadCheckInterval`|`Number (long)`|
+++
Sets the value of blocked thread check period, in ms.
+++
|[[clusterHost]]`clusterHost`|`String`|
+++
Set the hostname to be used for clustering.
+++
|[[clusterPingInterval]]`clusterPingInterval`|`Number (long)`|
+++
Set the value of cluster ping interval, in ms.
+++
|[[clusterPingReplyInterval]]`clusterPingReplyInterval`|`Number (long)`|
+++
Set the value of cluster ping reply interval, in ms.
+++
|[[clusterPort]]`clusterPort`|`Number (int)`|
+++
Set the port to be used for clustering.
+++
|[[clusterPublicHost]]`clusterPublicHost`|`String`|
+++
Set the public facing hostname to be used for clustering.
 Sometimes, e.g. when running on certain clouds, the local address the server listens on for clustering is not the same
 address that other nodes connect to it at, as the OS / cloud infrastructure does some kind of proxying.
 If this is the case you can specify a public hostname which is different from the hostname the server listens at.
 The default value is null which means use the same as the cluster hostname.
+++
|[[clusterPublicPort]]`clusterPublicPort`|`Number (int)`|
+++
See link for an explanation.
+++
|[[clustered]]`clustered`|`Boolean`|
+++
Set whether or not the Vert.x instance will be clustered.
+++
|[[eventBusOptions]]`eventBusOptions`|`link:dataobjects.html#EventBusOptions[EventBusOptions]`|
+++
Sets the event bus configuration to configure the host, port, ssl...
+++
|[[eventLoopPoolSize]]`eventLoopPoolSize`|`Number (int)`|
+++
Set the number of event loop threads to be used by the Vert.x instance.
+++
|[[haEnabled]]`haEnabled`|`Boolean`|
+++
Set whether HA will be enabled on the Vert.x instance.
+++
|[[haGroup]]`haGroup`|`String`|
+++
Set the HA group to be used when HA is enabled.
+++
|[[internalBlockingPoolSize]]`internalBlockingPoolSize`|`Number (int)`|
+++
Set the value of internal blocking pool size
+++
|[[maxEventLoopExecuteTime]]`maxEventLoopExecuteTime`|`Number (long)`|
+++
Sets the value of max event loop execute time, in ns.
+++
|[[maxWorkerExecuteTime]]`maxWorkerExecuteTime`|`Number (long)`|
+++
Sets the value of max worker execute time, in ns.
+++
|[[metricsOptions]]`metricsOptions`|`link:dataobjects.html#MetricsOptions[MetricsOptions]`|
+++
Set the metrics options
+++
|[[quorumSize]]`quorumSize`|`Number (int)`|
+++
Set the quorum size to be used when HA is enabled.
+++
|[[warningExceptionTime]]`warningExceptionTime`|`Number (long)`|
+++
Set the threshold value above this, the blocked warning contains a stack trace.
+++
|[[workerPoolSize]]`workerPoolSize`|`Number (int)`|
+++
Set the maximum number of worker threads to be used by the Vert.x instance.
+++
|===

[[GoAway]]
== GoAway

++++
 A  frame.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[debugData]]`debugData`|`Buffer`|
+++
Set the additional debug data
+++
|[[errorCode]]`errorCode`|`Number (long)`|
+++
@return the  error code
+++
|[[lastStreamId]]`lastStreamId`|`Number (int)`|
+++
Set the last stream id.
+++
|===

[[Http2Settings]]
== Http2Settings

++++
 HTTP2 settings, the settings is initialized with the default HTTP/2 values.<p>

 The settings expose the parameters defined by the HTTP/2 specification, as well as extra settings for
 protocol extensions.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[headerTableSize]]`headerTableSize`|`Number (long)`|
+++
Set  HTTP/2 setting.
+++
|[[initialWindowSize]]`initialWindowSize`|`Number (int)`|
+++
Set the  HTTP/2 setting
+++
|[[maxConcurrentStreams]]`maxConcurrentStreams`|`Number (long)`|
+++
Set the  HTTP/2 setting
+++
|[[maxFrameSize]]`maxFrameSize`|`Number (int)`|
+++
Set the  HTTP/2 setting
+++
|[[maxHeaderListSize]]`maxHeaderListSize`|`Number (int)`|
+++
Set the  HTTP/2 setting
+++
|[[pushEnabled]]`pushEnabled`|`Boolean`|
+++
Set the  HTTP/2 setting
+++
|===

[[Argument]]
== Argument

++++
 Defines a command line argument. Unlike options, argument don't have names and are identified using an index. The
 first index is 0 (because we are in the computer world).
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[argName]]`argName`|`String`|
+++
Sets the argument name of this link.
+++
|[[defaultValue]]`defaultValue`|`String`|
+++
Sets the default value of this link.
+++
|[[description]]`description`|`String`|
+++
Sets the description of the link.
+++
|[[hidden]]`hidden`|`Boolean`|
+++
Sets whether or not the current link is hidden.
+++
|[[index]]`index`|`Number (int)`|
+++
Sets the argument index.
+++
|[[multiValued]]`multiValued`|`Boolean`|
+++
Sets whether or not the argument can receive several values. Only the last argument can receive several values.
+++
|[[required]]`required`|`Boolean`|
+++
Sets whether or not the current link is required.
+++
|===

[[NetClientOptions]]
== NetClientOptions

++++
 Options for configuring a link.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[connectTimeout]]`connectTimeout`|`Number (int)`|
+++
Set the connect timeout
+++
|[[crlPaths]]`crlPaths`|`Array of String`|
+++
Add a CRL path
+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Add a CRL value
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++
Add an enabled cipher suite
+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
Set the idle timeout, in seconds. zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Set the TCP receive buffer size
+++
|[[reconnectAttempts]]`reconnectAttempts`|`Number (int)`|
+++
Set the value of reconnect attempts
+++
|[[reconnectInterval]]`reconnectInterval`|`Number (long)`|
+++
Set the reconnect interval
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
Set the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Set the TCP send buffer size
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`ssl`|`Boolean`|
+++
Set whether SSL/TLS is enabled
+++
|[[sslEngine]]`sslEngine`|`link:enums.html#SSLEngine[SSLEngine]`|
+++
Set to use SSL engine implementation to use.
+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
Set whether TCP no delay is enabled
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
Set the value of traffic class
+++
|[[trustAll]]`trustAll`|`Boolean`|
+++
Set whether all server certificates should be trusted
+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[useAlpn]]`useAlpn`|`Boolean`|
+++
Set the ALPN usage.
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
Set whether Netty pooled buffers are enabled
+++
|===

[[PfxOptions]]
== PfxOptions

++++
 Key or trust store options configuring private key and/or certificates based on PKCS#12 files.
 <p>
 When used as a key store, it should point to a store containing a private key and its certificate.
 When used as a trust store, it should point to a store containing a list of accepted certificates.
 <p>

 The store can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = new HttpServerOptions();
 options.setPfxKeyCertOptions(new PfxOptions().setPath("/mykeystore.p12").setPassword("foo"));
 </pre>

 Or directly provided as a buffer:<p>

 <pre>
 Buffer store = vertx.fileSystem().readFileSync("/mykeystore.p12");
 options.setPfxKeyCertOptions(new PfxOptions().setValue(store).setPassword("foo"));
 </pre>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[password]]`password`|`String`|
+++
Set the password
+++
|[[path]]`path`|`String`|
+++
Set the path
+++
|[[value]]`value`|`Buffer`|
+++
Set the store as a buffer
+++
|===

[[Option]]
== Option

++++
 Models command line options. Options are values passed to a command line interface using -x or --x. Supported
 syntaxes depend on the parser.
 <p/>
 Short name is generally used with a single dash, while long name requires a double-dash.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[argName]]`argName`|`String`|
+++
Sets te arg name for this option.
+++
|[[choices]]`choices`|`Array of String`|
+++
Sets the list of values accepted by this option. If the value set by the user does not match once of these
 values, a link exception is thrown.
+++
|[[defaultValue]]`defaultValue`|`String`|
+++
Sets the default value of this option
+++
|[[description]]`description`|`String`|
+++
Sets te description of this option.
+++
|[[flag]]`flag`|`Boolean`|
+++
Configures the current link to be a flag. It will be evaluated to <code>true</code> if it's found in
 the command line. If you need a flag that may receive a value, use, in this order:
 <code><pre>
   option.setFlag(true).setSingleValued(true)
 </pre></code>
+++
|[[help]]`help`|`Boolean`|
+++
Sets whether or not this option is a "help" option
+++
|[[hidden]]`hidden`|`Boolean`|
+++
Sets whether or not this option should be hidden
+++
|[[longName]]`longName`|`String`|
+++
Sets the long name of this option.
+++
|[[multiValued]]`multiValued`|`Boolean`|
+++
Sets whether or not this option can receive several values.
+++
|[[name]]`name`|`String`|
+++
@return the option name. It returns the long name if set, the short name otherwise. It cannot return <code>null</code> for valid option
+++
|[[required]]`required`|`Boolean`|
+++
Sets whether or not this option is mandatory.
+++
|[[shortName]]`shortName`|`String`|
+++
Sets the short name of this option.
+++
|[[singleValued]]`singleValued`|`Boolean`|
+++
Sets whether or not this option can receive a value.
+++
|===

[[NetServerOptions]]
== NetServerOptions

++++
 Options for configuring a link.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[acceptBacklog]]`acceptBacklog`|`Number (int)`|
+++
Set the accept back log
+++
|[[clientAuth]]`clientAuth`|`link:enums.html#ClientAuth[ClientAuth]`|
+++
Set whether client auth is required
+++
|[[clientAuthRequired]]`clientAuthRequired`|`Boolean`|
+++
Set whether client auth is required
+++
|[[crlPaths]]`crlPaths`|`Array of String`|
+++
Add a CRL path
+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Add a CRL value
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++
Add an enabled cipher suite
+++
|[[host]]`host`|`String`|
+++
Set the host
+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
Set the idle timeout, in seconds. zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[port]]`port`|`Number (int)`|
+++
Set the port
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
Set the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Set the TCP send buffer size
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`ssl`|`Boolean`|
+++
Set whether SSL/TLS is enabled
+++
|[[sslEngine]]`sslEngine`|`link:enums.html#SSLEngine[SSLEngine]`|
+++
Set to use SSL engine implementation to use.
+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
Set whether TCP no delay is enabled
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
Set the value of traffic class
+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[useAlpn]]`useAlpn`|`Boolean`|
+++
Set the ALPN usage.
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
Set whether Netty pooled buffers are enabled
+++
|===

[[MetricsOptions]]
== MetricsOptions

++++
 Vert.x metrics base configuration, this class can be extended by provider implementations to configure
 those specific implementations.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[enabled]]`enabled`|`Boolean`|
+++
Set whether metrics will be enabled on the Vert.x instance.
+++
|===

[[ClientOptionsBase]]
== ClientOptionsBase

++++
 Base class for Client options
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[connectTimeout]]`connectTimeout`|`Number (int)`|
+++
Set the connect timeout
+++
|[[crlPaths]]`crlPaths`|`Array of String`|
+++
Add a CRL path
+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Add a CRL value
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++
Add an enabled cipher suite
+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
Set the idle timeout, in seconds. zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
Set the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Set the TCP send buffer size
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`ssl`|`Boolean`|
+++
Set whether SSL/TLS is enabled
+++
|[[sslEngine]]`sslEngine`|`link:enums.html#SSLEngine[SSLEngine]`|
+++
Set to use SSL engine implementation to use.
+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
Set whether TCP no delay is enabled
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
Set the value of traffic class
+++
|[[trustAll]]`trustAll`|`Boolean`|
+++
Set whether all server certificates should be trusted
+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[useAlpn]]`useAlpn`|`Boolean`|
+++
Set the ALPN usage.
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
Set whether Netty pooled buffers are enabled
+++
|===

[[DeploymentOptions]]
== DeploymentOptions

++++
 Options for configuring a verticle deployment.
 <p>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`config`|`Json object`|
+++
Set the JSON configuration that will be passed to the verticle(s) when it's deployed
+++
|[[extraClasspath]]`extraClasspath`|`Array of String`|
+++
Set any extra classpath to be used when deploying the verticle.
 <p>
 Ignored if no isolation group is set.
+++
|[[ha]]`ha`|`Boolean`|
+++
Set whether the verticle(s) will be deployed as HA.
+++
|[[instances]]`instances`|`Number (int)`|
+++
Set the number of instances that should be deployed.
+++
|[[isolatedClasses]]`isolatedClasses`|`Array of String`|
+++
Set the isolated class names.
+++
|[[isolationGroup]]`isolationGroup`|`String`|
+++
Set the isolation group that will be used when deploying the verticle(s)
+++
|[[multiThreaded]]`multiThreaded`|`Boolean`|
+++
Set whether the verticle(s) should be deployed as a multi-threaded worker verticle
+++
|[[worker]]`worker`|`Boolean`|
+++
Set whether the verticle(s) should be deployed as a worker verticle
+++
|===

[[PemKeyCertOptions]]
== PemKeyCertOptions

++++
 Key store options configuring a private key and its certificate based on
 <i>Privacy-enhanced Electronic Email</i> (PEM) files.
 <p>

 The key file must contain a <b>non encrypted</b> private key in <b>PKCS8</b> format wrapped in a PEM
 block, for example:
 <p>

 <pre>
 -----BEGIN PRIVATE KEY-----
 MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDV6zPk5WqLwS0a
 ...
 K5xBhtm1AhdnZjx5KfW3BecE
 -----END PRIVATE KEY-----
 </pre><p>

 The certificate file must contain an X.509 certificate wrapped in a PEM block, for example:
 <p>

 <pre>
 -----BEGIN CERTIFICATE-----
 MIIDezCCAmOgAwIBAgIEZOI/3TANBgkqhkiG9w0BAQsFADBuMRAwDgYDVQQGEwdV
 ...
 +tmLSvYS39O2nqIzzAUfztkYnUlZmB0l/mKkVqbGJA==
 -----END CERTIFICATE-----
 </pre>

 The key and certificate can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = new HttpServerOptions();
 options.setPemKeyCertOptions(new PemKeyCertOptions().setKeyPath("/mykey.pem").setCertPath("/mycert.pem"));
 </pre>

 Or directly provided as a buffer:<p>

 <pre>
 Buffer key = vertx.fileSystem().readFileSync("/mykey.pem");
 Buffer cert = vertx.fileSystem().readFileSync("/mycert.pem");
 options.setPemKeyCertOptions(new PemKeyCertOptions().setKeyValue(key).setCertValue(cert));
 </pre>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[certPath]]`certPath`|`String`|
+++
Set the path to the certificate
+++
|[[certValue]]`certValue`|`Buffer`|
+++
Set the certificate as a buffer
+++
|[[keyPath]]`keyPath`|`String`|
+++
Set the path to the key file
+++
|[[keyValue]]`keyValue`|`Buffer`|
+++
Set the key a a buffer
+++
|===

[[HttpServerOptions]]
== HttpServerOptions

++++
 Represents options used by an link instance
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[acceptBacklog]]`acceptBacklog`|`Number (int)`|
+++
Set the accept back log
+++
|[[alpnVersions]]`alpnVersions`|`Array of link:enums.html#HttpVersion[HttpVersion]`|
+++
Set the list of protocol versions to provide to the server during the Application-Layer Protocol Negotiatiation.
+++
|[[clientAuth]]`clientAuth`|`link:enums.html#ClientAuth[ClientAuth]`|
+++
Set whether client auth is required
+++
|[[clientAuthRequired]]`clientAuthRequired`|`Boolean`|
+++
Set whether client auth is required
+++
|[[compressionSupported]]`compressionSupported`|`Boolean`|
+++
Set whether the server supports compression
+++
|[[crlPaths]]`crlPaths`|`Array of String`|
+++
Add a CRL path
+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Add a CRL value
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++
Add an enabled cipher suite
+++
|[[handle100ContinueAutomatically]]`handle100ContinueAutomatically`|`Boolean`|
+++
Set whether 100 Continue should be handled automatically
+++
|[[host]]`host`|`String`|
+++
Set the host
+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
Set the idle timeout, in seconds. zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.
+++
|[[initialSettings]]`initialSettings`|`link:dataobjects.html#Http2Settings[Http2Settings]`|
+++
Set the HTTP/2 connection settings immediatly sent by the server when a client connects.
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[maxChunkSize]]`maxChunkSize`|`Number (int)`|
+++
Set the maximum HTTP chunk size
+++
|[[maxHeaderSize]]`maxHeaderSize`|`Number (int)`|
+++
Set the maximum length of all headers for HTTP/1.x .
+++
|[[maxInitialLineLength]]`maxInitialLineLength`|`Number (int)`|
+++
Set the maximum length of the initial line for HTTP/1.x (e.g. <code>"GET / HTTP/1.0"</code>)
+++
|[[maxWebsocketFrameSize]]`maxWebsocketFrameSize`|`Number (int)`|
+++
Set the maximum websocket frames size
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[port]]`port`|`Number (int)`|
+++
Set the port
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
Set the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Set the TCP send buffer size
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`ssl`|`Boolean`|
+++
Set whether SSL/TLS is enabled
+++
|[[sslEngine]]`sslEngine`|`link:enums.html#SSLEngine[SSLEngine]`|
+++
Set to use SSL engine implementation to use.
+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
Set whether TCP no delay is enabled
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
Set the value of traffic class
+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[useAlpn]]`useAlpn`|`Boolean`|
+++
Set the ALPN usage.
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
Set whether Netty pooled buffers are enabled
+++
|[[websocketSubProtocols]]`websocketSubProtocols`|`String`|
+++
Set the websocket subprotocols supported by the server.
+++
|===

[[EventBusOptions]]
== EventBusOptions

++++
 Options to configure the event bus.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[acceptBacklog]]`acceptBacklog`|`Number (int)`|
+++
Set the accept back log.
+++
|[[clientAuth]]`clientAuth`|`link:enums.html#ClientAuth[ClientAuth]`|
+++
Set whether client auth is required
+++
|[[clusterPingInterval]]`clusterPingInterval`|`Number (long)`|
+++
Set the value of cluster ping interval, in ms.
+++
|[[clusterPingReplyInterval]]`clusterPingReplyInterval`|`Number (long)`|
+++
Set the value of cluster ping reply interval, in ms.
+++
|[[clusterPublicHost]]`clusterPublicHost`|`String`|
+++
Set the public facing hostname to be used for clustering.
 Sometimes, e.g. when running on certain clouds, the local address the server listens on for clustering is
 not the same address that other nodes connect to it at, as the OS / cloud infrastructure does some kind of
 proxying. If this is the case you can specify a public hostname which is different from the hostname the
 server listens at.
 <p>
 The default value is null which means use the same as the cluster hostname.
+++
|[[clusterPublicPort]]`clusterPublicPort`|`Number (int)`|
+++
See link for an explanation.
+++
|[[clustered]]`clustered`|`Boolean`|
+++
Sets whether or not the event bus is clustered.
+++
|[[connectTimeout]]`connectTimeout`|`Number (int)`|
+++
Sets the connect timeout
+++
|[[crlPaths]]`crlPaths`|`Array of String`|
+++
Add a CRL path
+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Add a CRL value
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++
Add an enabled cipher suite
+++
|[[host]]`host`|`String`|
+++
Sets the host.
+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
Set the idle timeout, in seconds. zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[port]]`port`|`Number (int)`|
+++
Sets the port.
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Set the TCP receive buffer size
+++
|[[reconnectAttempts]]`reconnectAttempts`|`Number (int)`|
+++
Sets the value of reconnect attempts.
+++
|[[reconnectInterval]]`reconnectInterval`|`Number (long)`|
+++
Set the reconnect interval.
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
Set the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Set the TCP send buffer size
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`ssl`|`Boolean`|
+++
Set whether SSL/TLS is enabled
+++
|[[sslEngine]]`sslEngine`|`link:enums.html#SSLEngine[SSLEngine]`|
+++
Set to use SSL engine implementation to use.
+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
Set whether TCP no delay is enabled
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
Set the value of traffic class
+++
|[[trustAll]]`trustAll`|`Boolean`|
+++
Set whether all server certificates should be trusted.
+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[useAlpn]]`useAlpn`|`Boolean`|
+++
Set the ALPN usage.
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
Set whether Netty pooled buffers are enabled
+++
|===

[[DatagramSocketOptions]]
== DatagramSocketOptions

++++
 Options used to configure a datagram socket.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[broadcast]]`broadcast`|`Boolean`|
+++
Set if the socket can receive broadcast packets
+++
|[[ipV6]]`ipV6`|`Boolean`|
+++
Set if IP v6 should be used
+++
|[[loopbackModeDisabled]]`loopbackModeDisabled`|`Boolean`|
+++
Set if loopback mode is disabled
+++
|[[multicastNetworkInterface]]`multicastNetworkInterface`|`String`|
+++
Set the multicast network interface address
+++
|[[multicastTimeToLive]]`multicastTimeToLive`|`Number (int)`|
+++
Set the multicast ttl value
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
Set the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Set the TCP send buffer size
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
Set the value of traffic class
+++
|===

[[HttpClientOptions]]
== HttpClientOptions

++++
 Options describing how an link will make connections.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[alpnVersions]]`alpnVersions`|`Array of link:enums.html#HttpVersion[HttpVersion]`|
+++
Set the list of protocol versions to provide to the server during the Application-Layer Protocol Negotiatiation.
 When the list is empty, the client provides a best effort list according to link:

 <ul>
   <li>: [ "h2", "http/1.1" ]</li>
   <li>otherwise: [link]</li>
 </ul>
+++
|[[connectTimeout]]`connectTimeout`|`Number (int)`|
+++
Set the connect timeout
+++
|[[crlPaths]]`crlPaths`|`Array of String`|
+++
Add a CRL path
+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Add a CRL value
+++
|[[defaultHost]]`defaultHost`|`String`|
+++
Set the default host name to be used by this client in requests if none is provided when making the request.
+++
|[[defaultPort]]`defaultPort`|`Number (int)`|
+++
Set the default port to be used by this client in requests if none is provided when making the request.
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++
Add an enabled cipher suite
+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
Set the idle timeout, in seconds. zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.
+++
|[[initialSettings]]`initialSettings`|`link:dataobjects.html#Http2Settings[Http2Settings]`|
+++
Set the HTTP/2 connection settings immediatly sent by to the server when the client connects.
+++
|[[keepAlive]]`keepAlive`|`Boolean`|
+++
Set whether keep alive is enabled on the client
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[maxChunkSize]]`maxChunkSize`|`Number (int)`|
+++
Set the maximum HTTP chunk size
+++
|[[maxPoolSize]]`maxPoolSize`|`Number (int)`|
+++
Set the maximum pool size for connections
+++
|[[maxWaitQueueSize]]`maxWaitQueueSize`|`Number (int)`|
+++
Set the maximum requests allowed in the wait queue, any requests beyond the max size will result in
 a ConnectionPoolTooBusyException.  If the value is set to a negative number then the queue will be unbounded.
+++
|[[maxWebsocketFrameSize]]`maxWebsocketFrameSize`|`Number (int)`|
+++
Set the max websocket frame size
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[pipelining]]`pipelining`|`Boolean`|
+++
Set whether pipe-lining is enabled on the client
+++
|[[protocolVersion]]`protocolVersion`|`link:enums.html#HttpVersion[HttpVersion]`|
+++
Set the protocol version.
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
Set the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Set the TCP send buffer size
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`ssl`|`Boolean`|
+++
Set whether SSL/TLS is enabled
+++
|[[sslEngine]]`sslEngine`|`link:enums.html#SSLEngine[SSLEngine]`|
+++
Set to use SSL engine implementation to use.
+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
Set whether TCP no delay is enabled
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
Set the value of traffic class
+++
|[[trustAll]]`trustAll`|`Boolean`|
+++
Set whether all server certificates should be trusted
+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[tryUseCompression]]`tryUseCompression`|`Boolean`|
+++
Set whether compression is enabled
+++
|[[useAlpn]]`useAlpn`|`Boolean`|
+++
Set the ALPN usage.
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
Set whether Netty pooled buffers are enabled
+++
|[[verifyHost]]`verifyHost`|`Boolean`|
+++
Set whether hostname verification is enabled
+++
|===

[[PemTrustOptions]]
== PemTrustOptions

++++
 Certificate Authority options configuring certificates based on
 <i>Privacy-enhanced Electronic Email</i> (PEM) files. The options is configured with a list of
 validating certificates.
 <p>
 Validating certificates must contain X.509 certificates wrapped in a PEM block:<p>

 <pre>
 -----BEGIN CERTIFICATE-----
 MIIDezCCAmOgAwIBAgIEVmLkwTANBgkqhkiG9w0BAQsFADBuMRAwDgYDVQQGEwdV
 ...
 z5+DuODBJUQst141Jmgq8bS543IU/5apcKQeGNxEyQ==
 -----END CERTIFICATE-----
 </pre>

 The certificates can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = new HttpServerOptions();
 options.setPemTrustOptions(new PemTrustOptions().addCertPath("/cert.pem"));
 </pre>

 Or directly provided as a buffer:
 <p>

 <pre>
 Buffer cert = vertx.fileSystem().readFileSync("/cert.pem");
 HttpServerOptions options = new HttpServerOptions();
 options.setPemTrustOptions(new PemTrustOptions().addCertValue(cert));
 </pre>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[certPaths]]`certPaths`|`Array of String`|
+++
Add a certificate path
+++
|[[certValues]]`certValues`|`Array of Buffer`|
+++
Add a certificate value
+++
|===

[[TCPSSLOptions]]
== TCPSSLOptions

++++
 Base class. TCP and SSL related options
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[crlPaths]]`crlPaths`|`Array of String`|
+++
Add a CRL path
+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Add a CRL value
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++
Add an enabled cipher suite
+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
Set the idle timeout, in seconds. zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Set the TCP receive buffer size
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
Set the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Set the TCP send buffer size
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++
Set whether SO_linger keep alive is enabled
+++
|[[ssl]]`ssl`|`Boolean`|
+++
Set whether SSL/TLS is enabled
+++
|[[sslEngine]]`sslEngine`|`link:enums.html#SSLEngine[SSLEngine]`|
+++
Set to use SSL engine implementation to use.
+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
Set whether TCP keep alive is enabled
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
Set whether TCP no delay is enabled
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
Set the value of traffic class
+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[useAlpn]]`useAlpn`|`Boolean`|
+++
Set the ALPN usage.
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
Set whether Netty pooled buffers are enabled
+++
|===

