= Cheatsheets

[[NetworkOptions]]
== NetworkOptions

++++
 @author <a href="http://tfox.org">Tim Fox</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Return the TCP receive buffer size, in bytes
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
@return  the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Return the TCP send buffer size, in bytes.
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
@return  the value of traffic class
+++
|===

[[DeliveryOptions]]
== DeliveryOptions

++++
 Delivery options are used to configure message delivery.
 <p>
 Delivery options allow to configure delivery timeout and message codec name, and to provide any headers
 that you wish to send with the message.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[codecName]]`codecName`|`String`|
+++
Get the codec name.
 <p>
 When sending or publishing a message a codec name can be provided. This must correspond with a previously registered
 message codec. This allows you to send arbitrary objects on the event bus (e.g. POJOs).
+++
|[[sendTimeout]]`sendTimeout`|`Number (long)`|
+++
Get the send timeout.
 <p>
 When sending a message with a response handler a send timeout can be provided. If no response is received
 within the timeout the handler will be called with a failure.
+++
|===

[[OpenOptions]]
== OpenOptions

++++
 Describes how an link should be opened.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[create]]`create`|`Boolean`|
+++
Should the file be created if it does not already exist?
+++
|[[createNew]]`createNew`|`Boolean`|
+++
Should the file be created if and the open fail if it already exists?
+++
|[[deleteOnClose]]`deleteOnClose`|`Boolean`|
+++
Should the file be deleted when it's closed, or the JVM is shutdown.
+++
|[[dsync]]`dsync`|`Boolean`|
+++
If true then every write to the file's content will be written synchronously to the underlying hardware.
+++
|[[perms]]`perms`|`String`|
+++
Get the permissions string to be used if creating a file
+++
|[[read]]`read`|`Boolean`|
+++
Is the file to opened for reading?
+++
|[[sparse]]`sparse`|`Boolean`|
+++
Set whether a hint should be provided that the file to created is sparse
+++
|[[sync]]`sync`|`Boolean`|
+++
If true then every write to the file's content and metadata will be written synchronously to the underlying hardware.
+++
|[[truncateExisting]]`truncateExisting`|`Boolean`|
+++
If the file exists and is opened for writing should the file be truncated to zero length on open?
+++
|[[write]]`write`|`Boolean`|
+++
Is the file to opened for writing?
+++
|===

[[JksOptions]]
== JksOptions

++++
 Key or trust store options configuring private key and/or certificates based on Java Keystore files.
 <p>
 When used as a key store, it should point to a store containing a private key and its certificate.
 When used as a trust store, it should point to a store containing a list of trusted certificates.
 <p>
 The store can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = HttpServerOptions.httpServerOptions();
 options.setKeyStore(JKSOptions.options().setPath("/mykeystore.jks").setPassword("foo"));
 </pre>

 Or directly provided as a buffer:
 <p>

 <pre>
 Buffer store = vertx.fileSystem().readFileSync("/mykeystore.jks");
 options.setKeyStore(JKSOptions.options().setValue(store).setPassword("foo"));
 </pre>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[password]]`password`|`String`|
+++
@return the password for the key store
+++
|[[path]]`path`|`String`|
+++
Get the path to the ksy store
+++
|[[value]]`value`|`Buffer`|
+++
Get the key store as a buffer
+++
|===

[[VertxOptions]]
== VertxOptions

++++
 Instances of this class are used to configure link instances.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[blockedThreadCheckInterval]]`blockedThreadCheckInterval`|`Number (long)`|
+++
Get the value of blocked thread check period, in ms.
 <p>
 This setting determines how often Vert.x will check whether event loop threads are executing for too long.
+++
|[[clusterHost]]`clusterHost`|`String`|
+++
Get the host name to be used for clustering.
+++
|[[clusterPingInterval]]`clusterPingInterval`|`Number (long)`|
+++
Get the value of cluster ping interval, in ms.
 <p>
 Nodes in the cluster ping each other at this interval to determine whether they are still running.
+++
|[[clusterPingReplyInterval]]`clusterPingReplyInterval`|`Number (long)`|
+++
Get the value of cluster ping reply interval, in ms.
 <p>
 After sending a ping, if a pong is not received in this time, the node will be considered dead.
+++
|[[clusterPort]]`clusterPort`|`Number (int)`|
+++
Get the port to be used for clustering
+++
|[[clusterPublicHost]]`clusterPublicHost`|`String`|
+++
Get the public facing hostname to be used when clustering.
+++
|[[clusterPublicPort]]`clusterPublicPort`|`Number (int)`|
+++
Get the public facing port to be used when clustering.
+++
|[[clustered]]`clustered`|`Boolean`|
+++
Is the Vert.x instance clustered?
+++
|[[eventLoopPoolSize]]`eventLoopPoolSize`|`Number (int)`|
+++
Get the number of event loop threads to be used by the Vert.x instance.
+++
|[[haEnabled]]`haEnabled`|`Boolean`|
+++
Will HA be enabled on the Vert.x instance?
+++
|[[haGroup]]`haGroup`|`String`|
+++
Get the HA group to be used when HA is enabled.
+++
|[[internalBlockingPoolSize]]`internalBlockingPoolSize`|`Number (int)`|
+++
Get the value of internal blocking pool size.
 <p>
 Vert.x maintains a pool for internal blocking operations
+++
|[[maxEventLoopExecuteTime]]`maxEventLoopExecuteTime`|`Number (long)`|
+++
Get the value of max event loop execute time, in ns.
 <p>
 Vert.x will automatically log a warning if it detects that event loop threads haven't returned within this time.
 <p>
 This can be used to detect where the user is blocking an event loop thread, contrary to the Golden Rule of the
 holy Event Loop.
+++
|[[maxWorkerExecuteTime]]`maxWorkerExecuteTime`|`Number (long)`|
+++
Get the value of max worker execute time, in ns.
 <p>
 Vert.x will automatically log a warning if it detects that worker threads haven't returned within this time.
 <p>
 This can be used to detect where the user is blocking a worker thread for too long. Although worker threads
 can be blocked longer than event loop threads, they shouldn't be blocked for long periods of time.
+++
|[[metricsOptions]]`metricsOptions`|`link:dataobjects.html#MetricsOptions[MetricsOptions]`|
+++
@return the metrics options
+++
|[[quorumSize]]`quorumSize`|`Number (int)`|
+++
Get the quorum size to be used when HA is enabled.
+++
|[[warningExceptionTime]]`warningExceptionTime`|`Number (long)`|
+++
Get the threshold value above this, the blocked warning contains a stack trace.
+++
|[[workerPoolSize]]`workerPoolSize`|`Number (int)`|
+++
Get the maximum number of worker threads to be used by the Vert.x instance.
 <p>
 Worker threads are used for running blocking code and worker verticles.
+++
|===

[[Argument]]
== Argument

++++
 Defines a command line argument. Unlike options, argument don't have names and are identified using an index. The
 first index is 0 (because we are in the computer world).
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[argName]]`argName`|`String`|
+++
@return the arg name, <code>null</code> if not defined.
+++
|[[defaultValue]]`defaultValue`|`String`|
+++
@return the argument default value, <code>null</code> if not specified.
+++
|[[description]]`description`|`String`|
+++
@return the description, <code>null</code> if not defined.
+++
|[[hidden]]`hidden`|`Boolean`|
+++
@return whether or not the current link is hidden.
+++
|[[index]]`index`|`Number (int)`|
+++
@return the argument index.
+++
|[[multiValued]]`multiValued`|`Boolean`|
+++
@return whether or not the argument can receive several values.
+++
|[[required]]`required`|`Boolean`|
+++
@return whether or not the current link is required.
+++
|===

[[NetClientOptions]]
== NetClientOptions

++++
 Options for configuring a link.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[connectTimeout]]`connectTimeout`|`Number (int)`|
+++
@return the value of connect timeout
+++
|[[crlPaths]]`crlPaths`|`Array of String`|
+++

+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Get the CRL values
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++

+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
@return  the idle timeout, in seconds
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Return the TCP receive buffer size, in bytes
+++
|[[reconnectAttempts]]`reconnectAttempts`|`Number (int)`|
+++
@return  the value of reconnect attempts
+++
|[[reconnectInterval]]`reconnectInterval`|`Number (long)`|
+++
@return  the value of reconnect interval
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
@return  the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Return the TCP send buffer size, in bytes.
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++

+++
|[[ssl]]`ssl`|`Boolean`|
+++

+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
@return is TCP keep alive enabled?
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
@return TCP no delay enabled ?
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
@return  the value of traffic class
+++
|[[trustAll]]`trustAll`|`Boolean`|
+++

+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
@return are Netty pooled buffers enabled?
+++
|===

[[PfxOptions]]
== PfxOptions

++++
 Key or trust store options configuring private key and/or certificates based on PKCS#12 files.
 <p>
 When used as a key store, it should point to a store containing a private key and its certificate.
 When used as a trust store, it should point to a store containing a list of accepted certificates.
 <p>

 The store can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = new HttpServerOptions();
 options.setPfxKeyCertOptions(new PfxOptions().setPath("/mykeystore.p12").setPassword("foo"));
 </pre>

 Or directly provided as a buffer:<p>

 <pre>
 Buffer store = vertx.fileSystem().readFileSync("/mykeystore.p12");
 options.setPfxKeyCertOptions(new PfxOptions().setValue(store).setPassword("foo"));
 </pre>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[password]]`password`|`String`|
+++
Get the password
+++
|[[path]]`path`|`String`|
+++
Get the path
+++
|[[value]]`value`|`Buffer`|
+++
Get the store as a buffer
+++
|===

[[Option]]
== Option

++++
 Models command line options. Options are values passed to a command line interface using -x or --x. Supported
 syntaxes depend on the parser.
 <p/>
 Short name is generally used with a single dash, while long name requires a double-dash.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[argName]]`argName`|`String`|
+++
@return the option arg name used in usage messages, <code>null</code> if not set.
+++
|[[choices]]`choices`|`Array of String`|
+++
@return get the list of choices for the given option. Empty if this option does not define choices.
+++
|[[defaultValue]]`defaultValue`|`String`|
+++
@return the default value of this option, <code>null</code> if not set.
+++
|[[description]]`description`|`String`|
+++
@return the description of this option, <code>null</code> if not set.
+++
|[[flag]]`flag`|`Boolean`|
+++
@return whether or not this option is a flag.
+++
|[[help]]`help`|`Boolean`|
+++
Checks whether or not this option is a "Help" option.
+++
|[[hidden]]`hidden`|`Boolean`|
+++
@return whtehr or not this option is hidden.
+++
|[[longName]]`longName`|`String`|
+++
@return the option long name, <code>null</code> if not set.
+++
|[[multiValued]]`multiValued`|`Boolean`|
+++
@return whether or not this option can receive several values.
+++
|[[name]]`name`|`String`|
+++
@return the option name. It returns the long name if set, the short name otherwise. It cannot return <code>null</code> for valid option
+++
|[[required]]`required`|`Boolean`|
+++
@return whether or not this option is mandatory.
+++
|[[shortName]]`shortName`|`String`|
+++
@return the short name of this option, <code>null</code> if not set.
+++
|[[singleValued]]`singleValued`|`Boolean`|
+++
@return whether or not this option is single valued.
+++
|===

[[NetServerOptions]]
== NetServerOptions

++++
 Options for configuring a link.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[acceptBacklog]]`acceptBacklog`|`Number (int)`|
+++
@return the value of accept backlog
+++
|[[clientAuth]]`clientAuth`|`link:enums.html#ClientAuth[ClientAuth]`|
+++
Set whether client auth is required
+++
|[[clientAuthRequired]]`clientAuthRequired`|`Boolean`|
+++

+++
|[[crlPaths]]`crlPaths`|`Array of String`|
+++

+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Get the CRL values
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++

+++
|[[host]]`host`|`String`|
+++

+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
@return  the idle timeout, in seconds
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[port]]`port`|`Number (int)`|
+++

+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Return the TCP receive buffer size, in bytes
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
@return  the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Return the TCP send buffer size, in bytes.
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++

+++
|[[ssl]]`ssl`|`Boolean`|
+++

+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
@return is TCP keep alive enabled?
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
@return TCP no delay enabled ?
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
@return  the value of traffic class
+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
@return are Netty pooled buffers enabled?
+++
|===

[[MetricsOptions]]
== MetricsOptions

++++
 Vert.x metrics base configuration, this class can be extended by provider implementations to configure
 those specific implementations.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[enabled]]`enabled`|`Boolean`|
+++
Will metrics be enabled on the Vert.x instance?
+++
|===

[[ClientOptionsBase]]
== ClientOptionsBase

++++
 Base class for Client options
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[connectTimeout]]`connectTimeout`|`Number (int)`|
+++
@return the value of connect timeout
+++
|[[crlPaths]]`crlPaths`|`Array of String`|
+++

+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Get the CRL values
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++

+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
@return  the idle timeout, in seconds
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Return the TCP receive buffer size, in bytes
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
@return  the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Return the TCP send buffer size, in bytes.
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++

+++
|[[ssl]]`ssl`|`Boolean`|
+++

+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
@return is TCP keep alive enabled?
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
@return TCP no delay enabled ?
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
@return  the value of traffic class
+++
|[[trustAll]]`trustAll`|`Boolean`|
+++

+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
@return are Netty pooled buffers enabled?
+++
|===

[[DeploymentOptions]]
== DeploymentOptions

++++
 Options for configuring a verticle deployment.
 <p>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`config`|`Json object`|
+++
Get the JSON configuration that will be passed to the verticle(s) when deployed.
+++
|[[extraClasspath]]`extraClasspath`|`Array of String`|
+++
Get any extra classpath to be used when deploying the verticle.
 <p>
 Ignored if no isolation group is set.
+++
|[[ha]]`ha`|`Boolean`|
+++
Will the verticle(s) be deployed as HA (highly available) ?
+++
|[[instances]]`instances`|`Number (int)`|
+++
Get the number of instances that should be deployed.
+++
|[[isolatedClasses]]`isolatedClasses`|`Array of String`|
+++
Get the list of isolated class names, the names can be a Java class fully qualified name such as
 'com.mycompany.myproject.engine.MyClass' or a wildcard matching such as `com.mycompany.myproject.*`.
+++
|[[isolationGroup]]`isolationGroup`|`String`|
+++
Get the isolation group that will be used when deploying the verticle(s)
+++
|[[multiThreaded]]`multiThreaded`|`Boolean`|
+++
Should the verticle(s) be deployed as a multi-threaded worker verticle?
 <p>
 Ignored if link is not true.
+++
|[[worker]]`worker`|`Boolean`|
+++
Should the verticle(s) be deployed as a worker verticle?
+++
|===

[[PemKeyCertOptions]]
== PemKeyCertOptions

++++
 Key store options configuring a private key and its certificate based on
 <i>Privacy-enhanced Electronic Email</i> (PEM) files.
 <p>

 The key file must contain a <b>non encrypted</b> private key in <b>PKCS8</b> format wrapped in a PEM
 block, for example:
 <p>

 <pre>
 -----BEGIN PRIVATE KEY-----
 MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDV6zPk5WqLwS0a
 ...
 K5xBhtm1AhdnZjx5KfW3BecE
 -----END PRIVATE KEY-----
 </pre><p>

 The certificate file must contain an X.509 certificate wrapped in a PEM block, for example:
 <p>

 <pre>
 -----BEGIN CERTIFICATE-----
 MIIDezCCAmOgAwIBAgIEZOI/3TANBgkqhkiG9w0BAQsFADBuMRAwDgYDVQQGEwdV
 ...
 +tmLSvYS39O2nqIzzAUfztkYnUlZmB0l/mKkVqbGJA==
 -----END CERTIFICATE-----
 </pre>

 The key and certificate can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = new HttpServerOptions();
 options.setPemKeyCertOptions(new PemKeyCertOptions().setKeyPath("/mykey.pem").setCertPath("/mycert.pem"));
 </pre>

 Or directly provided as a buffer:<p>

 <pre>
 Buffer key = vertx.fileSystem().readFileSync("/mykey.pem");
 Buffer cert = vertx.fileSystem().readFileSync("/mycert.pem");
 options.setPemKeyCertOptions(new PemKeyCertOptions().setKeyValue(key).setCertValue(cert));
 </pre>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[certPath]]`certPath`|`String`|
+++
Get the path to the certificate file
+++
|[[certValue]]`certValue`|`Buffer`|
+++
Get the certificate as a buffer
+++
|[[keyPath]]`keyPath`|`String`|
+++
Get the path to the key file
+++
|[[keyValue]]`keyValue`|`Buffer`|
+++
Get the key as a buffer
+++
|===

[[HttpServerOptions]]
== HttpServerOptions

++++
 Represents options used by an link instance
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[acceptBacklog]]`acceptBacklog`|`Number (int)`|
+++
@return the value of accept backlog
+++
|[[clientAuth]]`clientAuth`|`link:enums.html#ClientAuth[ClientAuth]`|
+++
Set whether client auth is required
+++
|[[clientAuthRequired]]`clientAuthRequired`|`Boolean`|
+++

+++
|[[compressionSupported]]`compressionSupported`|`Boolean`|
+++
@return true if the server supports compression
+++
|[[crlPaths]]`crlPaths`|`Array of String`|
+++

+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Get the CRL values
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++

+++
|[[handle100ContinueAutomatically]]`handle100ContinueAutomatically`|`Boolean`|
+++
@return whether 100 Continue should be handled automatically
+++
|[[host]]`host`|`String`|
+++

+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
@return  the idle timeout, in seconds
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[maxWebsocketFrameSize]]`maxWebsocketFrameSize`|`Number (int)`|
+++
@return  the maximum websocket framesize
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[port]]`port`|`Number (int)`|
+++

+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Return the TCP receive buffer size, in bytes
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
@return  the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Return the TCP send buffer size, in bytes.
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++

+++
|[[ssl]]`ssl`|`Boolean`|
+++

+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
@return is TCP keep alive enabled?
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
@return TCP no delay enabled ?
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
@return  the value of traffic class
+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
@return are Netty pooled buffers enabled?
+++
|[[websocketSubProtocols]]`websocketSubProtocols`|`String`|
+++
@return Get the websocket subprotocols
+++
|===

[[DatagramSocketOptions]]
== DatagramSocketOptions

++++
 Options used to configure a datagram socket.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[broadcast]]`broadcast`|`Boolean`|
+++
@return true if the socket receive broadcast packets?
+++
|[[ipV6]]`ipV6`|`Boolean`|
+++
@return  true if IP v6 be used?
+++
|[[loopbackModeDisabled]]`loopbackModeDisabled`|`Boolean`|
+++
@return true if loopback mode is disabled
+++
|[[multicastNetworkInterface]]`multicastNetworkInterface`|`String`|
+++
Get the multicast network interface address
+++
|[[multicastTimeToLive]]`multicastTimeToLive`|`Number (int)`|
+++
@return the multicast ttl value
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Return the TCP receive buffer size, in bytes
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
@return  the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Return the TCP send buffer size, in bytes.
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
@return  the value of traffic class
+++
|===

[[HttpClientOptions]]
== HttpClientOptions

++++
 Options describing how an link will make connections.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[connectTimeout]]`connectTimeout`|`Number (int)`|
+++
@return the value of connect timeout
+++
|[[crlPaths]]`crlPaths`|`Array of String`|
+++

+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Get the CRL values
+++
|[[defaultHost]]`defaultHost`|`String`|
+++
Get the default host name to be used by this client in requests if none is provided when making the request.
+++
|[[defaultPort]]`defaultPort`|`Number (int)`|
+++
Get the default port to be used by this client in requests if none is provided when making the request.
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++

+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
@return  the idle timeout, in seconds
+++
|[[keepAlive]]`keepAlive`|`Boolean`|
+++
Is keep alive enabled on the client?
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[maxPoolSize]]`maxPoolSize`|`Number (int)`|
+++
Get the maximum pool size for connections
+++
|[[maxWebsocketFrameSize]]`maxWebsocketFrameSize`|`Number (int)`|
+++
Get the maximum websocket framesize to use
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[pipelining]]`pipelining`|`Boolean`|
+++
Is pipe-lining enabled on the client
+++
|[[protocolVersion]]`protocolVersion`|`link:enums.html#HttpVersion[HttpVersion]`|
+++
Get the protocol version.
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Return the TCP receive buffer size, in bytes
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
@return  the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Return the TCP send buffer size, in bytes.
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++

+++
|[[ssl]]`ssl`|`Boolean`|
+++

+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
@return is TCP keep alive enabled?
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
@return TCP no delay enabled ?
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
@return  the value of traffic class
+++
|[[trustAll]]`trustAll`|`Boolean`|
+++

+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[tryUseCompression]]`tryUseCompression`|`Boolean`|
+++
Is compression enabled on the client?
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
@return are Netty pooled buffers enabled?
+++
|[[verifyHost]]`verifyHost`|`Boolean`|
+++
Is hostname verification (for SSL/TLS) enabled?
+++
|===

[[PemTrustOptions]]
== PemTrustOptions

++++
 Certificate Authority options configuring certificates based on
 <i>Privacy-enhanced Electronic Email</i> (PEM) files. The options is configured with a list of
 validating certificates.
 <p>
 Validating certificates must contain X.509 certificates wrapped in a PEM block:<p>

 <pre>
 -----BEGIN CERTIFICATE-----
 MIIDezCCAmOgAwIBAgIEVmLkwTANBgkqhkiG9w0BAQsFADBuMRAwDgYDVQQGEwdV
 ...
 z5+DuODBJUQst141Jmgq8bS543IU/5apcKQeGNxEyQ==
 -----END CERTIFICATE-----
 </pre>

 The certificates can either be loaded by Vert.x from the filesystem:
 <p>
 <pre>
 HttpServerOptions options = new HttpServerOptions();
 options.setPemTrustOptions(new PemTrustOptions().addCertPath("/cert.pem"));
 </pre>

 Or directly provided as a buffer:
 <p>

 <pre>
 Buffer cert = vertx.fileSystem().readFileSync("/cert.pem");
 HttpServerOptions options = new HttpServerOptions();
 options.setPemTrustOptions(new PemTrustOptions().addCertValue(cert));
 </pre>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[certPaths]]`certPaths`|`Array of String`|
+++
@return  the certificate paths used to locate certificates
+++
|[[certValues]]`certValues`|`Array of Buffer`|
+++

+++
|===

[[TCPSSLOptions]]
== TCPSSLOptions

++++
 Base class. TCP and SSL related options
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[crlPaths]]`crlPaths`|`Array of String`|
+++

+++
|[[crlValues]]`crlValues`|`Array of Buffer`|
+++
Get the CRL values
+++
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|
+++

+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|
+++
@return  the idle timeout, in seconds
+++
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the key/cert options in jks format, aka Java keystore.
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|
+++
Set the key/cert store options in pem format.
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options in pem format
+++
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the key/cert options in pfx format.
+++
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|
+++
Set the trust options in pfx format
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|
+++
Return the TCP receive buffer size, in bytes
+++
|[[reuseAddress]]`reuseAddress`|`Boolean`|
+++
@return  the value of reuse address
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|
+++
Return the TCP send buffer size, in bytes.
+++
|[[soLinger]]`soLinger`|`Number (int)`|
+++

+++
|[[ssl]]`ssl`|`Boolean`|
+++

+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
@return is TCP keep alive enabled?
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
@return TCP no delay enabled ?
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|
+++
@return  the value of traffic class
+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|
+++
Set the trust options in jks format, aka Java trustore
+++
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|
+++
@return are Netty pooled buffers enabled?
+++
|===

