= Enums

[[HttpVersion]]
== HttpVersion

++++
 Represents the version of the HTTP protocol.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[HTTP_1_0]]`HTTP_1_0`|-
|[[HTTP_1_1]]`HTTP_1_1`|-
|[[HTTP_2]]`HTTP_2`|-
|===

[[SSLEngine]]
== SSLEngine

++++
 The SSL engine implementation to use in a Vert.x server or client.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[JDK]]`JDK`|
+++
Use the engine provided by the JDK.
+++
|[[OPENSSL]]`OPENSSL`|
+++
Use an OpenSSL based engine.
+++
|===

[[HttpMethod]]
== HttpMethod

++++
 Represents an HTTP method
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[OPTIONS]]`OPTIONS`|-
|[[GET]]`GET`|-
|[[HEAD]]`HEAD`|-
|[[POST]]`POST`|-
|[[PUT]]`PUT`|-
|[[DELETE]]`DELETE`|-
|[[TRACE]]`TRACE`|-
|[[CONNECT]]`CONNECT`|-
|[[PATCH]]`PATCH`|-
|[[UNKNOWN]]`UNKNOWN`|-
|===

[[ClientAuth]]
== ClientAuth

++++
 Configures the engine to require/request client authentication. Following are the options :
 <p>
 NONE - No client authentication is requested or required.
 <p>
 REQUEST - Accept authentication if presented by client. If this option is set and the client chooses
      not to provide authentication information about itself, the negotiations will continue.
 <p>
 REQUIRED - Require client to present authentication, if not presented then negotiations will be declined.
 <p>
 Created by manishk on 10/2/2015.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NONE]]`NONE`|-
|[[REQUEST]]`REQUEST`|-
|[[REQUIRED]]`REQUIRED`|-
|===

[[DnsResponseCode]]
== DnsResponseCode

++++
 Represents the possible response codes a server may send after receiving a
 query. A response code of 0 indicates no error.

++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NOERROR]]`NOERROR`|
+++
ID 0, no error
+++
|[[FORMERROR]]`FORMERROR`|
+++
ID 1, format error
+++
|[[SERVFAIL]]`SERVFAIL`|
+++
ID 2, server failure
+++
|[[NXDOMAIN]]`NXDOMAIN`|
+++
ID 3, name error
+++
|[[NOTIMPL]]`NOTIMPL`|
+++
ID 4, not implemented
+++
|[[REFUSED]]`REFUSED`|
+++
ID 5, operation refused
+++
|[[YXDOMAIN]]`YXDOMAIN`|
+++
ID 6, domain name should not exist
+++
|[[YXRRSET]]`YXRRSET`|
+++
ID 7, resource record set should not exist
+++
|[[NXRRSET]]`NXRRSET`|
+++
ID 8, rrset does not exist
+++
|[[NOTAUTH]]`NOTAUTH`|
+++
ID 9, not authoritative for zone
+++
|[[NOTZONE]]`NOTZONE`|
+++
ID 10, name not in zone
+++
|[[BADVERS]]`BADVERS`|
+++
ID 11, bad extension mechanism for version
+++
|[[BADSIG]]`BADSIG`|
+++
ID 12, bad signature
+++
|[[BADKEY]]`BADKEY`|
+++
ID 13, bad key
+++
|[[BADTIME]]`BADTIME`|
+++
ID 14, bad timestamp
+++
|===

[[ReplyFailure]]
== ReplyFailure

++++
 Represents the type of reply failure
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[TIMEOUT]]`TIMEOUT`|
+++
The message send failed because no reply was received before the timeout time.
+++
|[[NO_HANDLERS]]`NO_HANDLERS`|
+++
The message send failed because no handlers were available to handle the message.
+++
|[[RECIPIENT_FAILURE]]`RECIPIENT_FAILURE`|
+++
The message send failed because the recipient actively sent back a failure (rejected the message)
+++
|===

[[WebsocketVersion]]
== WebsocketVersion

++++
 Represents the WebSocket version
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[V00]]`V00`|-
|[[V07]]`V07`|-
|[[V08]]`V08`|-
|[[V13]]`V13`|-
|===

