#!/bin/sh

# This script is used only for generating python documentation for vert.x

PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# The path to this script from the place it was called
DIRNAME=`dirname "$PRG"`
CURRDIR=`pwd`
cd "$CURRDIR"

CLASSPATH=\
$DIRNAME/conf:\
$DIRNAME/target/vert.x-core.jar:\
$DIRNAME/target/vert.x-platform.jar:\
$DIRNAME/lib/main/netty.jar:\
$DIRNAME/lib/main/jackson-core-asl.jar:\
$DIRNAME/lib/main/jackson-mapper-asl.jar:\
$DIRNAME/lib/main/hazelcast.jar:\
$DIRNAME/src/main/python:\

jython -J-classpath $CLASSPATH -Dpython.path=src/main/python pydocx.py
