#!/bin/sh

# This script lives on the vert.x bin directory which should be on the users PATH

PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

DIRNAME=`dirname "$PRG"`

# Change this if you are using a different Groovy version
GROOVY_VERSION=1.8.1

CLASSPATH=$DIRNAME/../conf:$DIRNAME/../lib/java/vert.x.jar:$DIRNAME/../lib/java/netty.jar:\
$DIRNAME/../lib/java/hazelcast.jar:$DIRNAME/../lib/java/jackson-core.jar:\
$DIRNAME/../lib/java/jackson-mapper.jar:\
$DIRNAME/../lib/java/js.jar:$DIRNAME/../lib/ruby:$DIRNAME/../lib/javascript:\
$JRUBY_HOME/lib/jruby.jar:$GROOVY_HOME/embeddable/groovy-all-$GROOVY_VERSION.jar

java -Djava.util.logging.config.file=$DIRNAME/../conf/logging.properties -Djruby.home=$JRUBY_HOME\
 -cp $CLASSPATH org.vertx.java.core.app.cli.VertxMgr "$@"
