#!/bin/sh

# This script lives on the vert.x install directory which should be on the users PATH
# It is called like java e.g. vertx-java -cp "somepath" org.foo.MyMainClass

# We need to figure out what this directory is relative to wherever this is called from. Remember this dir is on the path
# so this script can be called from anywhere

PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

DIRNAME=`dirname "$PRG"`

EXTRA_CLASSPATH=$DIRNAME/../lib/java/vert.x.jar:$DIRNAME/../lib/java/netty.jar:$DIRNAME/../lib/java/high-scale-lib.jar

# We need to append the EXTRA_CLASSPATH to any classpath specified on the command line

NEW_ARGS=
APPEND_CP=false
for arg in "$@"
do
  if $APPEND_CP ; then
    arg=$arg:$EXTRA_CLASSPATH
    APPEND_CP=false    
  fi
  if [ $arg = "-cp" ] || [ $arg = "-classpath" ]; then
    APPEND_CP=true
  fi
  NEW_ARGS=$NEW_ARGS" "$arg
done

java -Djava.util.logging.config.file=$DIRNAME/../logging.properties $NEW_ARGS
