#!/bin/sh

# This script lives on the vert.x bin directory which should be on the users PATH

PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

if [ "x" == "x$VERTX_BOOT_DEBUG" ]; then
  VERTX_BOOT_DEBUG="false"
fi

# The path to this script from the place it was called
DIRNAME=`dirname "$PRG"`
VERTX_DIR=`dirname "$DIRNAME"`

# The absolute path of this script
CURRDIR=`pwd`
SCRIPTDIR=`cd $DIRNAME;pwd`
cd $CURRDIR

java -Djava.util.logging.config.file=$VERTX_DIR/conf/logging.properties \
-Dvertx.boot.debug=$VERTX_BOOT_DEBUG \
-Dvertx.home=$VERTX_DIR \
-Dvertx.install=$VERTX_DIR \
-Djruby.home=$JRUBY_HOME \
-jar $VERTX_DIR/bin/vert.x-boot.jar "$@"
