#!/bin/sh

# This script lives on the vert.x bin directory which should be on the users PATH

PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# The path to this script from the place it was called
DIRNAME=`dirname "$PRG"`
VERTX_DIR=`dirname "$DIRNAME"`

# The absolute path of this script
CURRDIR=`pwd`
SCRIPTDIR=`cd $DIRNAME;pwd`
cd $CURRDIR

java -Dvertx.home=$VERTX_DIR -Djava.util.logging.config.file=$DIRNAME/../conf/logging.properties -Djruby.home=$JRUBY_HOME \
-Dvertx.mods=$VERTX_MODS -Dvertx.install=$SCRIPTDIR/.. -jar $VERTX_DIR/bin/vert.x-boot.jar "$@"
