#!/bin/sh

# This script lives on the vert.x install directory which should be on the users PATH

PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

DIRNAME=`dirname "$PRG"`

CLASSPATH=$DIRNAME/../lib/java/vert.x.jar:$DIRNAME/../lib/java/netty.jar:$DIRNAME/../lib/java/high-scale-lib.jar

java -Djava.util.logging.config.file=$DIRNAME/../logging.properties -cp $CLASSPATH org.vertx.java.core.appmanager.AppManager
