== HttpClientOptions

++++
 Options describing how an link will make connections.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description

|[[connectTimeout]]`connectTimeout`
|`Number (int)`
|+++
Set the connect timeout+++

|[[crlPaths]]`crlPaths`
|`Array of String`
|+++
Add a CRL path+++

|[[crlValues]]`crlValues`
|`Array of Buffer`
|+++
Add a CRL value+++

|[[defaultHost]]`defaultHost`
|`String`
|+++
Set the default host name to be used by this client in requests if none is provided when making the request.+++

|[[defaultPort]]`defaultPort`
|`Number (int)`
|+++
Set the default port to be used by this client in requests if none is provided when making the request.+++

|[[enabledCipherSuites]]`enabledCipherSuites`
|`Array of String`
|+++
Add an enabled cipher suite+++

|[[idleTimeout]]`idleTimeout`
|`Number (int)`
|+++
Set the idle timeout, in seconds. zero means don't timeout.
 This determines if a connection will timeout and be closed if no data is received within the timeout.+++

|[[keepAlive]]`keepAlive`
|`Boolean`
|+++
Set whether keep alive is enabled on the client+++

|[[keyStoreOptions]]`keyStoreOptions`
|`link:JksOptions.html[JksOptions]`
|+++
Set the key/cert options in jks format, aka Java keystore.+++

|[[maxPoolSize]]`maxPoolSize`
|`Number (int)`
|+++
Set the maximum pool size for connections+++

|[[maxWebsocketFrameSize]]`maxWebsocketFrameSize`
|`Number (int)`
|+++
Set the max websocket frame size+++

|[[pemKeyCertOptions]]`pemKeyCertOptions`
|`link:PemKeyCertOptions.html[PemKeyCertOptions]`
|+++
Set the key/cert store options in pem format.+++

|[[pemTrustOptions]]`pemTrustOptions`
|`link:PemTrustOptions.html[PemTrustOptions]`
|+++
Set the trust options in pem format+++

|[[pfxKeyCertOptions]]`pfxKeyCertOptions`
|`link:PfxOptions.html[PfxOptions]`
|+++
Set the key/cert options in pfx format.+++

|[[pfxTrustOptions]]`pfxTrustOptions`
|`link:PfxOptions.html[PfxOptions]`
|+++
Set the trust options in pfx format+++

|[[pipelining]]`pipelining`
|`Boolean`
|+++
Set whether pipe-lining is enabled on the client+++

|[[protocolVersion]]`protocolVersion`
|`Enum`
|+++
Set the protocol version.+++

|[[receiveBufferSize]]`receiveBufferSize`
|`Number (int)`
|+++
Set the TCP receive buffer size+++

|[[reuseAddress]]`reuseAddress`
|`Boolean`
|+++
Set the value of reuse address+++

|[[sendBufferSize]]`sendBufferSize`
|`Number (int)`
|+++
Set the TCP send buffer size+++

|[[soLinger]]`soLinger`
|`Number (int)`
|+++
Set whether SO_linger keep alive is enabled+++

|[[ssl]]`ssl`
|`Boolean`
|+++
Set whether SSL/TLS is enabled+++

|[[tcpKeepAlive]]`tcpKeepAlive`
|`Boolean`
|+++
Set whether TCP keep alive is enabled+++

|[[tcpNoDelay]]`tcpNoDelay`
|`Boolean`
|+++
Set whether TCP no delay is enabled+++

|[[trafficClass]]`trafficClass`
|`Number (int)`
|+++
Set the value of traffic class+++

|[[trustAll]]`trustAll`
|`Boolean`
|+++
Set whether all server certificates should be trusted+++

|[[trustStoreOptions]]`trustStoreOptions`
|`link:JksOptions.html[JksOptions]`
|+++
Set the trust options in jks format, aka Java trustore+++

|[[tryUseCompression]]`tryUseCompression`
|`Boolean`
|+++
Set whether compression is enabled+++

|[[usePooledBuffers]]`usePooledBuffers`
|`Boolean`
|+++
Set whether Netty pooled buffers are enabled+++

|[[verifyHost]]`verifyHost`
|`Boolean`
|+++
Set whether hostname verification is enabled+++
|===
