== HttpClientOptions

++++
 Options describing how an link will make connections.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description

|`sendBufferSize`
|`Number`
|+++
Set the TCP send buffer size+++

|`receiveBufferSize`
|`Number`
|+++
Set the TCP receive buffer size+++

|`reuseAddress`
|`Boolean`
|+++
Set the value of reuse address+++

|`trafficClass`
|`Number`
|+++
Set the value of traffic class+++

|`tcpNoDelay`
|`Boolean`
|+++
Set whether TCP no delay is enabled+++

|`tcpKeepAlive`
|`Boolean`
|+++
Set whether TCP keep alive is enabled+++

|`soLinger`
|`Number`
|+++
Set whether SO_linger keep alive is enabled+++

|`usePooledBuffers`
|`Boolean`
|+++
Set whether Netty pooled buffers are enabled+++

|`idleTimeout`
|`Number`
|-
|`ssl`
|`Boolean`
|+++
Set whether SSL/TLS is enabled+++

|`keyStoreOptions`
|`link:JksOptions.html[JksOptions]`
|+++
Set the key/cert options in jks format, aka Java keystore.+++

|`pfxKeyCertOptions`
|`link:PfxOptions.html[PfxOptions]`
|+++
Set the key/cert options in pfx format.+++

|`pemKeyCertOptions`
|`link:PemKeyCertOptions.html[PemKeyCertOptions]`
|+++
Set the key/cert store options in pem format.+++

|`trustStoreOptions`
|`link:JksOptions.html[JksOptions]`
|+++
Set the trust options in jks format, aka Java trustore+++

|`pfxTrustOptions`
|`link:PfxOptions.html[PfxOptions]`
|+++
Set the trust options in pfx format+++

|`pemTrustOptions`
|`link:PemTrustOptions.html[PemTrustOptions]`
|+++
Set the trust options in pem format+++

|`enabledCipherSuites`
|`Array of String`
|+++
Add an enabled cipher suite+++

|`crlPaths`
|`Array of String`
|+++
Add a CRL path+++

|`connectTimeout`
|`Number`
|+++
Set the connect timeout+++

|`trustAll`
|`Boolean`
|+++
Set whether all server certificates should be trusted+++

|`maxPoolSize`
|`Number`
|+++
Set the maximum pool size for connections+++

|`keepAlive`
|`Boolean`
|+++
Set whether keep alive is enabled on the client+++

|`pipelining`
|`Boolean`
|+++
Set whether pipe-lining is enabled on the client+++

|`verifyHost`
|`Boolean`
|+++
Set whether hostname verification is enabled+++

|`tryUseCompression`
|`Boolean`
|+++
Set whether compression is enabled+++

|`maxWebsocketFrameSize`
|`Number`
|+++
Set the max websocket frame size+++

|`defaultHost`
|`String`
|+++
Set the default host name to be used by this client in requests if none is provided when making the request.+++

|`defaultPort`
|`Number`
|+++
Set the default port to be used by this client in requests if none is provided when making the request.+++
|===
