== OpenOptions

++++
 Describes how an link should be opened.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description

|[[perms]]`perms`
|`String`
|+++
Set the permissions string+++

|[[read]]`read`
|`Boolean`
|+++
Set whether the file is to be opened for reading+++

|[[write]]`write`
|`Boolean`
|+++
Set whether the file is to be opened for writing+++

|[[create]]`create`
|`Boolean`
|+++
Set whether the file should be created if it does not already exist.+++

|[[createNew]]`createNew`
|`Boolean`
|+++
Set whether the file should be created and fail if it does exist already.+++

|[[deleteOnClose]]`deleteOnClose`
|`Boolean`
|+++
Set whether the file should be deleted when it's closed, or the JVM is shutdown.+++

|[[truncateExisting]]`truncateExisting`
|`Boolean`
|+++
Set whether the file should be truncated to zero length on opening if it exists and is opened for write+++

|[[sparse]]`sparse`
|`Boolean`
|+++
Set whether a hint should be provided that the file to created is sparse+++

|[[sync]]`sync`
|`Boolean`
|+++
Set whether every write to the file's content and meta-data will be written synchronously to the underlying hardware.+++

|[[dSync]]`dSync`
|`Boolean`
|+++
Set whether every write to the file's content  ill be written synchronously to the underlying hardware.+++
|===
