== OptionModel

++++
 Models command line options. Options are values passed to a command line interface using -x or --x. Supported
 syntaxes depend on the parser.
 <p/>
 Short name is generally used with a single dash, while long name requires a double-dash.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description

|[[argName]]`argName`
|`String`
|+++
Sets te arg name for this option.+++

|[[defaultValue]]`defaultValue`
|`String`
|+++
Sets the default value of this option+++

|[[description]]`description`
|`String`
|+++
Sets te description of this option.+++

|[[flag]]`flag`
|`Boolean`
|+++
Configures the current link to be a flag. It will be evaluated to <code>true</code> if it's found in
 the command line. If you need a flag that may receive a value, use, in this order:
 <code><pre>
   option.setFlag(true).setSingleValued(true)
 </pre></code>+++

|[[hidden]]`hidden`
|`Boolean`
|+++
Sets whether or not this option should be hidden+++

|[[longName]]`longName`
|`String`
|+++
Sets the long name of this option.+++

|[[multiValued]]`multiValued`
|`Boolean`
|+++
Sets whether or not this option can receive several values.+++

|[[required]]`required`
|`Boolean`
|+++
Sets whether or not this option is mandatory.+++

|[[shortName]]`shortName`
|`String`
|+++
Sets the short name of this option.+++

|[[singleValued]]`singleValued`
|`Boolean`
|+++
Sets whether or not this option can receive a value.+++
|===
