== VertxOptions

++++
 Instances of this class are used to configure link instances.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description

|[[blockedThreadCheckInterval]]`blockedThreadCheckInterval`
|`Number (long)`
|+++
Sets the value of blocked thread check period, in ms.+++

|[[clusterHost]]`clusterHost`
|`String`
|+++
Set the hostname to be used for clustering.+++

|[[clusterPingInterval]]`clusterPingInterval`
|`Number (long)`
|+++
Set the value of cluster ping interval, in ms.+++

|[[clusterPingReplyInterval]]`clusterPingReplyInterval`
|`Number (long)`
|+++
Set the value of cluster ping reply interval, in ms.+++

|[[clusterPort]]`clusterPort`
|`Number (int)`
|+++
Set the port to be used for clustering.+++

|[[clusterPublicHost]]`clusterPublicHost`
|`String`
|+++
Set the public facing hostname to be used for clustering.
 Sometimes, e.g. when running on certain clouds, the local address the server listens on for clustering is not the same
 address that other nodes connect to it at, as the OS / cloud infrastructure does some kind of proxying.
 If this is the case you can specify a public hostname which is different from the hostname the server listens at.
 The default value is null which means use the same as the cluster hostname.+++

|[[clusterPublicPort]]`clusterPublicPort`
|`Number (int)`
|+++
See link for an explanation.+++

|[[clustered]]`clustered`
|`Boolean`
|+++
Set whether or not the Vert.x instance will be clustered.+++

|[[eventLoopPoolSize]]`eventLoopPoolSize`
|`Number (int)`
|+++
Set the number of event loop threads to be used by the Vert.x instance.+++

|[[haEnabled]]`haEnabled`
|`Boolean`
|+++
Set whether HA will be enabled on the Vert.x instance.+++

|[[haGroup]]`haGroup`
|`String`
|+++
Set the HA group to be used when HA is enabled.+++

|[[internalBlockingPoolSize]]`internalBlockingPoolSize`
|`Number (int)`
|+++
Set the value of internal blocking pool size+++

|[[maxEventLoopExecuteTime]]`maxEventLoopExecuteTime`
|`Number (long)`
|+++
Sets the value of max event loop execute time, in ns.+++

|[[maxWorkerExecuteTime]]`maxWorkerExecuteTime`
|`Number (long)`
|+++
Sets the value of max worker execute time, in ns.+++

|[[metricsOptions]]`metricsOptions`
|`link:MetricsOptions.html[MetricsOptions]`
|+++
Set the metrics options+++

|[[quorumSize]]`quorumSize`
|`Number (int)`
|+++
Set the quorum size to be used when HA is enabled.+++

|[[warningExceptionTime]]`warningExceptionTime`
|`Number (long)`
|+++
Set the threshold value above this, the blocked warning contains a stack trace.+++

|[[workerPoolSize]]`workerPoolSize`
|`Number (int)`
|+++
Set the maximum number of worker threads to be used by the Vert.x instance.+++
|===
