=== Passing configuration to a verticle

Configuration in the form of JSON can be passed to a verticle at deployment time:

[source,java]
----
JsonObject config = new JsonObject().put("name", "tim").put("directory", "/blah");
DeploymentOptions options = new DeploymentOptions().setConfig(config);
vertx.deployVerticle("com.mycompany.MyOrderProcessorVerticle", options);
----

This configuration is then available via the `link:../../apidocs/io/vertx/core/Context.html[Context]` object or directly using the
`link:../../apidocs/io/vertx/core/AbstractVerticle.html#config--[config]` method.

The configuration is returned as a JSON object so you
can retrieve data as follows:

[source,java]
----
System.out.println("Configuration: " + config().getString("name"));
----

=== Accessing environment variables in a Verticle

Environment variables and system properties are accessible from a verticle by following the Java way. To
retrieve system properties, use `link:../../apidocs/java/lang/System.html#getProperty-java.lang.String-[System.getProperty]`
(or `link:../../apidocs/java/lang/System.html#getProperty-java.lang.String-java.lang.String-[System.getProperty]`). You can also retrieve the
environment variables using `link:../../apidocs/java/lang/System.html#getenv-java.lang.String-[System.getenv]`.