#!/bin/sh

# This script is used only for running vert.x to run examples from the development source tree

PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# The path to this script from the place it was called
DIRNAME=`dirname "$PRG"`

# The absolute path of this script

CURRDIR=`pwd`
SCRIPTDIR=`cd $DIRNAME;pwd`
cd $CURRDIR

CLASSPATH=\
$DIRNAME/../../conf:\
$DIRNAME/../../target/vert.x-core.jar:\
$DIRNAME/../../target/vert.x-platform.jar:\
$DIRNAME/../../lib/main/netty.jar:\
$DIRNAME/../../lib/main/jackson-core-asl.jar:\
$DIRNAME/../../lib/main/jackson-mapper-asl.jar:\
$DIRNAME/../../lib/main/hazelcast.jar:\
$DIRNAME/../../lib/main/jruby.jar:\
$DIRNAME/../../lib/main/js.jar:\
$DIRNAME/../../lib/main/groovy-all.jar:\
$DIRNAME/../../src/main/ruby:\
$DIRNAME/../../src/main/javascript

MODS_DIR=$SCRIPTDIR/../../target/dist-build/vert.x-1.0.beta10/mods

SERVER_OPTS="-server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -Xms500M -Xmx500M"

java $SERVER_OPTS -Djava.util.logging.config.file=$DIRNAME/../../conf/logging.properties -Djruby.home=$JRUBY_HOME \
-Dvertx.mods=$MODS_DIR -cp $CLASSPATH org.vertx.java.deploy.impl.cli.VertxMgr "$@"
