#!/bin/sh

# This script is used only for running vert.x to run examples from the development source tree

PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

DIRNAME=`dirname "$PRG"`

CLASSPATH=\
$DIRNAME/../../conf:\
$DIRNAME/../../target/vert.x.jar:\
$DIRNAME/../../lib/main/netty.jar:\
$DIRNAME/../../lib/main/jackson-core-asl-1.9.4.jar:\
$DIRNAME/../../lib/main/jackson-mapper-asl-1.9.4.jar:\
$DIRNAME/../../lib/main/hazelcast-1.9.4.4.jar:\
$DIRNAME/../../lib/main/jruby.jar:\
$DIRNAME/../../lib/main/js.jar:\
$DIRNAME/../../lib/main/mail.jar:\
$DIRNAME/../../lib/main/mongo.jar:\
$DIRNAME/../../lib/main/groovy-all-1.8.6.jar:\
$DIRNAME/../../lib/main/jruby.jar:\
$DIRNAME/../../src/main/ruby:\
$DIRNAME/../../src/main/javascript

java -Djava.util.logging.config.file=$DIRNAME/../../conf/logging.properties -Djruby.home=$JRUBY_HOME\
 -cp $CLASSPATH org.vertx.java.core.deploy.impl.cli.VertxMgr "$@"
