name: CI
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: 'string'
      jdk:
        default: 8
        type: 'string'
      os:
        default: ubuntu-latest
        type: 'string'
      profile:
        default: ''
        type: 'string'
      io_uring_supported:
        default: false
        type: boolean
jobs:
  Test:
    name: Run tests
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.jdk }}
          distribution: temurin
      - name: Run tests
        if: ${{ runner.os != 'Linux' || inputs.profile != '-PNativeIoUring'}}
        run: mvn -s .github/maven-ci-settings.xml -q clean verify -B ${{ inputs.profile }}
      - name: Run tests
        if: ${{ runner.os == 'Linux' && inputs.profile == '-PNativeIoUring' && inputs.io_uring_supported }}
        run: |
          # io_uring testing requires more locked memory for kernel ring buffers than the default 8MB limit
          sudo prlimit --pid $$ --memlock=16777216:16777216
          mvn -s .github/maven-ci-settings.xml -q clean verify -B ${{ inputs.profile }}
